module.exports =
  BRUSH: 'brush'
  SPRAY: 'spray'

  STATES_LENGTH: 6

  BRUSH_WIDTH_MIN: 1
  BRUSH_WIDTH_MAX: 100
  BRUSH_WIDTH_INIT: 10
  BRUSH_WIDTH_STEP: 1

  BRUSH_OPACITY_MIN: 10
  BRUSH_OPACITY_MAX: 100
  BRUSH_OPACITY_INIT: 100
  BRUSH_OPACITY_STEP: 1

  BRUSH_COLOR_INIT: '#333'
  DO_ACTIONS_DELAY: 250
