/**
 * Connections
 * (sails.config.constants)
 */

module.exports.constants = {
  MAX_LEVEL_DIFFERENCE: 3,
  GAME_DURATION: 10,
  GAME_APPLICATION_DURATION: 10,
  GAME_APPLICATION_CRONTAB_TIMEOUT: 3,
  RESIDUE_TIME_TRESHOLD_FOR_GAME_SEARCH: 5,
  RESIDUE_TIME_FOR_ESTIMATOR_BOTS: 4,
  RESIDUE_TIME_FOR_PAINTER_BOTS: 6,
  NEW_LEVEL_EXPERIENCE_STEP_VALUE: 500,
  GAME_WON_EXPERIENCE_VALUE: 500
}