export default {
  GAME_WON_EXPERIENCE_VALUE: 50,
  GAME_DURATION: 240,
  GAME_APPLICATION_DURATION: 10,
  RESIDUE_TIME_FOR_ESTIMATOR_BOTS: 4,
  RESIDUE_TIME_FOR_PAINTER_BOTS: 6,
  GAME_APPLICATION_CRONTAB_TIMEOUT: 3,
  RESIDUE_TIME_TRESHOLD_FOR_GAME_SEARCH: 5,
};
